[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# Включаем проверку ошибок (E), предупреждений (W), импортов (I) и стилистики (F)
select = ["E", "F", "I", "W"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double" # Использовать двойные кавычки (как в Black)
